version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: baekon
      POSTGRES_PASSWORD: baekon
      POSTGRES_DB: baekon
    ports: [ "5432:5432" ]
  qdrant:
    image: qdrant/qdrant:v1.8.4
    ports: [ "6333:6333" ]
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: [ "9000:9000", "9001:9001" ]
    volumes:
      - ./data/minio:/data
